### ISSUE TITLE
Make SKYNotification.subscriptionID public

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-SDK-iOS#41]
Re-open it from oursky/skygear-SDK-iOS#260

-[SKYNotification subscriptionID] is put inside a private header, it would be useful if we can get the subscription id from a notification.

We actually need it here: oursky/ufo#848

**Comment by b123400** [comment]
In patron, we need to subscribe to multiple subscriptions. We want to identify them by the subscriptionID, but in the app delegate callback, we can only access the SKYNotification object, cannot access the "subscriptionID" property, because it is put inside a private header. Which means we only know there is an update from subscriptions, but we don't know which subscription does it come from. We workaround it by importing the private header (as you can see in PR), but this is not very good...
